using System.Text;
using System.Text.Json;

static string FindRepoRoot(string startDir)
{
    var dir = new DirectoryInfo(startDir);
    while (dir is not null)
    {
        var candidate = Path.Combine(dir.FullName, "schema", "schema.json");
        if (File.Exists(candidate))
            return dir.FullName;
        dir = dir.Parent;
    }

    throw new DirectoryNotFoundException("Could not locate repo root (schema/schema.json not found).");
}

var repoRoot = FindRepoRoot(AppContext.BaseDirectory);
var schemaPath = Path.Combine(repoRoot, "schema", "schema.json");
var outDir = Path.Combine(repoRoot, "src", "Agent.Acp", "Generated", "Unions");
Directory.CreateDirectory(outDir);

var json = await File.ReadAllTextAsync(schemaPath, Encoding.UTF8);
using var doc = JsonDocument.Parse(json);
var defs = doc.RootElement.GetProperty("$defs");

GenerateContentBlock(defs, Path.Combine(outDir, "ContentBlock.Union.g.cs"));
GenerateSessionUpdate(defs, Path.Combine(outDir, "SessionUpdate.Union.g.cs"));
GenerateToolCallContent(defs, Path.Combine(outDir, "ToolCallContent.Union.g.cs"));

Console.WriteLine($"Generated unions into: {outDir}");

static void GenerateContentBlock(JsonElement defs, string outFile)
{
    var union = defs.GetProperty("ContentBlock");
    var oneOf = union.GetProperty("oneOf");

    // ContentBlock uses discriminator: type
    var discriminator = "type";

    var variants = new List<(string DiscriminatorValue, string DefName)>();
    foreach (var item in oneOf.EnumerateArray())
    {
        var allOf0 = item.GetProperty("allOf")[0];
        var @ref = allOf0.GetProperty("$ref").GetString()!; // #/$defs/TextContent
        var defName = @ref.Split('/').Last();
        var discVal = item.GetProperty("properties").GetProperty(discriminator).GetProperty("const").GetString()!;
        variants.Add((discVal, defName));
    }

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated />");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("using System.Text.Json;");
    sb.AppendLine("using System.Text.Json.Serialization;");
    sb.AppendLine();
    sb.AppendLine("namespace Agent.Acp.Schema;");
    sb.AppendLine();
    sb.AppendLine("/// <summary>Discriminated union for ACP ContentBlock.</summary>");
    sb.AppendLine("[JsonConverter(typeof(ContentBlockJsonConverter))]");
    sb.AppendLine("public abstract partial class ContentBlock { }");
    sb.AppendLine();
    sb.AppendLine("/// <summary>Fallback for unknown/extension variants.</summary>");
    sb.AppendLine("public sealed partial class UnknownContentBlock : ContentBlock");
    sb.AppendLine("{");
    sb.AppendLine("    public UnknownContentBlock(JsonElement raw) => Raw = raw;");
    sb.AppendLine("    public JsonElement Raw { get; }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Concrete variants are declared in schema as TextContent, ImageContent, ...
    // We generate them as partials inheriting from ContentBlock so other generated code can reference them.
    foreach (var v in variants)
    {
        sb.AppendLine($"public partial class {v.DefName} : ContentBlock {{ }}");
    }

    sb.AppendLine();
    sb.AppendLine("public sealed class ContentBlockJsonConverter : JsonConverter<ContentBlock>");
    sb.AppendLine("{");
    sb.AppendLine("    public override ContentBlock Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
    sb.AppendLine("    {");
    sb.AppendLine("        using var doc = JsonDocument.ParseValue(ref reader);");
    sb.AppendLine("        var root = doc.RootElement;");
    sb.AppendLine($"        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty(\"{discriminator}\", out var d) || d.ValueKind != JsonValueKind.String)");
    sb.AppendLine("            return new UnknownContentBlock(root.Clone());");
    sb.AppendLine("        var dv = d.GetString();");
    sb.AppendLine("        return dv switch");
    sb.AppendLine("        {");
    foreach (var v in variants)
    {
        sb.AppendLine($"            \"{v.DiscriminatorValue}\" => JsonSerializer.Deserialize<{v.DefName}>(root, options)!,");
    }
    sb.AppendLine("            _ => new UnknownContentBlock(root.Clone()),");
    sb.AppendLine("        };");
    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine("    public override void Write(Utf8JsonWriter writer, ContentBlock value, JsonSerializerOptions options)");
    sb.AppendLine("    {");
    sb.AppendLine("        if (value is UnknownContentBlock u)");
    sb.AppendLine("        {");
    sb.AppendLine("            u.Raw.WriteTo(writer);");
    sb.AppendLine("            return;");
    sb.AppendLine("        }");
    sb.AppendLine("        JsonSerializer.Serialize(writer, (object)value, value.GetType(), options);");
    sb.AppendLine("    }");
    sb.AppendLine("}");

    File.WriteAllText(outFile, sb.ToString(), Encoding.UTF8);
}

static void GenerateToolCallContent(JsonElement defs, string outFile)
{
    var union = defs.GetProperty("ToolCallContent");
    var oneOf = union.GetProperty("oneOf");

    var discriminator = "type";

    // We generate schema-aligned concrete variant types that include both the discriminator
    // and the referenced base fields (Content/Diff/Terminal) because the schema composes them via allOf.
    // Unknown/extension variants are preserved as JsonElement.

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated />");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("using System.Text.Json;");
    sb.AppendLine("using System.Text.Json.Serialization;");
    sb.AppendLine();
    sb.AppendLine("namespace Agent.Acp.Schema;");
    sb.AppendLine();
    sb.AppendLine("/// <summary>Discriminated union for ACP ToolCallContent.</summary>");
    sb.AppendLine("[JsonConverter(typeof(ToolCallContentJsonConverter))]");
    sb.AppendLine("public abstract partial class ToolCallContent { }");
    sb.AppendLine();
    sb.AppendLine("/// <summary>Fallback for unknown/extension variants.</summary>");
    sb.AppendLine("public sealed partial class UnknownToolCallContent : ToolCallContent");
    sb.AppendLine("{");
    sb.AppendLine("    public UnknownToolCallContent(JsonElement raw) => Raw = raw;");
    sb.AppendLine("    public JsonElement Raw { get; }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Variant: type=content (fields: _meta, content)
    sb.AppendLine("public sealed partial class ToolCallContentContent : ToolCallContent");
    sb.AppendLine("{");
    sb.AppendLine("    [JsonPropertyName(\"type\")] public string Type { get; set; } = \"content\";");
    sb.AppendLine("    [JsonPropertyName(\"_meta\")] public object? _meta { get; set; } = default!;");
    sb.AppendLine("    [JsonPropertyName(\"content\")] public ContentBlock Content { get; set; } = default!;");
    sb.AppendLine("}");
    sb.AppendLine();

    // Variant: type=diff (fields: _meta, path, newText, oldText?)
    sb.AppendLine("public sealed partial class ToolCallContentDiff : ToolCallContent");
    sb.AppendLine("{");
    sb.AppendLine("    [JsonPropertyName(\"type\")] public string Type { get; set; } = \"diff\";");
    sb.AppendLine("    [JsonPropertyName(\"_meta\")] public object? _meta { get; set; } = default!;");
    sb.AppendLine("    [JsonPropertyName(\"path\")] public string Path { get; set; } = default!;");
    sb.AppendLine("    [JsonPropertyName(\"newText\")] public string NewText { get; set; } = default!;");
    sb.AppendLine("    [JsonPropertyName(\"oldText\")] public string? OldText { get; set; } = default!;");
    sb.AppendLine("}");
    sb.AppendLine();

    // Variant: type=terminal (fields: _meta, terminalId)
    sb.AppendLine("public sealed partial class ToolCallContentTerminal : ToolCallContent");
    sb.AppendLine("{");
    sb.AppendLine("    [JsonPropertyName(\"type\")] public string Type { get; set; } = \"terminal\";");
    sb.AppendLine("    [JsonPropertyName(\"_meta\")] public object? _meta { get; set; } = default!;");
    sb.AppendLine("    [JsonPropertyName(\"terminalId\")] public string TerminalId { get; set; } = default!;");
    sb.AppendLine("}");
    sb.AppendLine();

    sb.AppendLine("public sealed class ToolCallContentJsonConverter : JsonConverter<ToolCallContent>");
    sb.AppendLine("{");
    sb.AppendLine("    public override ToolCallContent Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
    sb.AppendLine("    {");
    sb.AppendLine("        using var doc = JsonDocument.ParseValue(ref reader);");
    sb.AppendLine("        var root = doc.RootElement;");
    sb.AppendLine("        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty(\"type\", out var d) || d.ValueKind != JsonValueKind.String)");
    sb.AppendLine("            return new UnknownToolCallContent(root.Clone());");
    sb.AppendLine("        var dv = d.GetString();");
    sb.AppendLine("        return dv switch");
    sb.AppendLine("        {");
    sb.AppendLine("            \"content\" => JsonSerializer.Deserialize<ToolCallContentContent>(root, options)!,");
    sb.AppendLine("            \"diff\" => JsonSerializer.Deserialize<ToolCallContentDiff>(root, options)!,");
    sb.AppendLine("            \"terminal\" => JsonSerializer.Deserialize<ToolCallContentTerminal>(root, options)!,");
    sb.AppendLine("            _ => new UnknownToolCallContent(root.Clone()),");
    sb.AppendLine("        };");
    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine("    public override void Write(Utf8JsonWriter writer, ToolCallContent value, JsonSerializerOptions options)");
    sb.AppendLine("    {");
    sb.AppendLine("        if (value is UnknownToolCallContent u)");
    sb.AppendLine("        {");
    sb.AppendLine("            u.Raw.WriteTo(writer);");
    sb.AppendLine("            return;");
    sb.AppendLine("        }");
    sb.AppendLine("        JsonSerializer.Serialize(writer, (object)value, value.GetType(), options);");
    sb.AppendLine("    }");
    sb.AppendLine("}");

    File.WriteAllText(outFile, sb.ToString(), Encoding.UTF8);
}

static void GenerateSessionUpdate(JsonElement defs, string outFile)
{
    var union = defs.GetProperty("SessionUpdate");
    var oneOf = union.GetProperty("oneOf");

    var discriminator = "sessionUpdate";

    // Variants are defined by discriminator value, but multiple variants reference the same $defs.ContentChunk.
    // For Option 1 we generate distinct derived types for the three chunk modes.
    var chunkDiscriminators = new HashSet<string> { "user_message_chunk", "agent_message_chunk", "agent_thought_chunk" };

    var variants = new List<(string DiscriminatorValue, string DefName)>();
    foreach (var item in oneOf.EnumerateArray())
    {
        var allOf0 = item.GetProperty("allOf")[0];
        var @ref = allOf0.GetProperty("$ref").GetString()!;
        var refDefName = @ref.Split('/').Last();
        var discVal = item.GetProperty("properties").GetProperty(discriminator).GetProperty("const").GetString()!;

        // Generate synthetic-but-stable schema-aligned names for chunk variants.
        if (refDefName == "ContentChunk" && chunkDiscriminators.Contains(discVal))
        {
            variants.Add((discVal, discVal switch
            {
                "user_message_chunk" => "UserMessageChunk",
                "agent_message_chunk" => "AgentMessageChunk",
                "agent_thought_chunk" => "AgentThoughtChunk",
                _ => refDefName,
            }));
        }
        else
        {
            variants.Add((discVal, refDefName));
        }
    }

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated />");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("using System.Text.Json;");
    sb.AppendLine("using System.Text.Json.Serialization;");
    sb.AppendLine();
    sb.AppendLine("namespace Agent.Acp.Schema;");
    sb.AppendLine();
    sb.AppendLine("/// <summary>Discriminated union for ACP SessionUpdate.</summary>");
    sb.AppendLine("[JsonConverter(typeof(SessionUpdateJsonConverter))]");
    sb.AppendLine("public abstract partial class SessionUpdate { }");
    sb.AppendLine();
    sb.AppendLine("/// <summary>Fallback for unknown/extension variants.</summary>");
    sb.AppendLine("public sealed partial class UnknownSessionUpdate : SessionUpdate");
    sb.AppendLine("{");
    sb.AppendLine("    public UnknownSessionUpdate(JsonElement raw) => Raw = raw;");
    sb.AppendLine("    public JsonElement Raw { get; }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Option 1: distinct chunk update types
    sb.AppendLine("public abstract partial class ContentChunkUpdateBase : SessionUpdate");
    sb.AppendLine("{");
    sb.AppendLine("    [JsonPropertyName(\"_meta\")] public object? _meta { get; set; } = default!;");
    sb.AppendLine("    [JsonPropertyName(\"content\")] public ContentBlock Content { get; set; } = default!;");
    sb.AppendLine("    [JsonPropertyName(\"sessionUpdate\")] public string SessionUpdate { get; set; } = default!;");
    sb.AppendLine("}");
    sb.AppendLine("public sealed partial class UserMessageChunk : ContentChunkUpdateBase { public UserMessageChunk() { SessionUpdate = \"user_message_chunk\"; } }");
    sb.AppendLine("public sealed partial class AgentMessageChunk : ContentChunkUpdateBase { public AgentMessageChunk() { SessionUpdate = \"agent_message_chunk\"; } }");
    sb.AppendLine("public sealed partial class AgentThoughtChunk : ContentChunkUpdateBase { public AgentThoughtChunk() { SessionUpdate = \"agent_thought_chunk\"; } }");
    sb.AppendLine();

    // Other variants are declared in schema as ToolCall, ToolCallUpdate, Plan, etc.
    // We generate them as partials inheriting from SessionUpdate so other generated code can reference them.
    foreach (var v in variants)
    {
        if (v.DefName is "UserMessageChunk" or "AgentMessageChunk" or "AgentThoughtChunk")
            continue;

        sb.AppendLine($"public partial class {v.DefName} : SessionUpdate {{ }}");
    }

    sb.AppendLine();
    sb.AppendLine("public sealed class SessionUpdateJsonConverter : JsonConverter<SessionUpdate>");
    sb.AppendLine("{");
    sb.AppendLine("    public override SessionUpdate Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
    sb.AppendLine("    {");
    sb.AppendLine("        using var doc = JsonDocument.ParseValue(ref reader);");
    sb.AppendLine("        var root = doc.RootElement;");
    sb.AppendLine($"        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty(\"{discriminator}\", out var d) || d.ValueKind != JsonValueKind.String)");
    sb.AppendLine("            return new UnknownSessionUpdate(root.Clone());");
    sb.AppendLine("        var dv = d.GetString();");
    sb.AppendLine("        return dv switch");
    sb.AppendLine("        {");

    foreach (var v in variants)
    {
        sb.AppendLine($"            \"{v.DiscriminatorValue}\" => JsonSerializer.Deserialize<{v.DefName}>(root, options)!,");
    }

    sb.AppendLine("            _ => new UnknownSessionUpdate(root.Clone()),");
    sb.AppendLine("        };");
    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine("    public override void Write(Utf8JsonWriter writer, SessionUpdate value, JsonSerializerOptions options)");
    sb.AppendLine("    {");
    sb.AppendLine("        if (value is UnknownSessionUpdate u)");
    sb.AppendLine("        {");
    sb.AppendLine("            u.Raw.WriteTo(writer);");
    sb.AppendLine("            return;");
    sb.AppendLine("        }");
    sb.AppendLine("        JsonSerializer.Serialize(writer, (object)value, value.GetType(), options);");
    sb.AppendLine("    }");
    sb.AppendLine("}");

    File.WriteAllText(outFile, sb.ToString(), Encoding.UTF8);
}
