#!/usr/bin/env python3
"""Patch NJsonSchema-generated C# to tighten union placeholder types.

NJsonSchema currently emits placeholder types (e.g. Content1) for union-heavy refs.
We patch a small, explicit set of properties to use the intended discriminated union
base types generated by UnionGen (e.g. ContentBlock).

This is intentionally simple and surgical: string replacements with assertions.
"""

from __future__ import annotations

from pathlib import Path


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    path = root / "src" / "Agent.Acp" / "Generated" / "AcpSchema.g.cs"

    s = path.read_text(encoding="utf-8")

    # ContentChunk.content and ContentChunk-like wrappers should use ContentBlock, not Content1.
    # These patterns are stable in the generated file.
    targets = {
        "public Content1 Content { get; set; } = default!;": "public ContentBlock Content { get; set; } = default!;",
        "public Content1 Content1 { get; set; } = default!;": "public ContentBlock Content1 { get; set; } = default!;",
    }

    for old, new in targets.items():
        if old not in s:
            raise SystemExit(f"Patch target not found: {old}")
        s = s.replace(old, new)

    path.write_text(s, encoding="utf-8")
    print(f"Patched: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
